// Game data: skins, maps, levels, modes and economy (see ZNAKEX_Game_Brief.md).
import { SKIN_LIST, BASIC_COLORS } from './skinlist.js';

export const COLS = 12;
export const ROWS = 18;

// ------------------------------------------------------------------ economy
export const ECONOMY = {
  startCoins: 2500, // demo only: enough to try the shop and a coin revive
  reviveCoins: [100, 200],
  levelReward: (map, level) => {
    const base = level <= 3 ? 40 : level <= 6 ? 55 : 75;
    return Math.round(base * (1 + 0.1 * (map - 1)));
  },
  replayReward: 5,
  classicCoinsPerOrbs: 5,
  frenzyCoinsPerOrbs: 3,
  duelReward: { easy: 15, medium: 30, hard: 60 },
  duelPaidWinsPerDay: 5,
  wheel: [
    { v: 10, w: 15 }, { v: 15, w: 25 }, { v: 20, w: 18 }, { v: 10, w: 15 },
    { v: 30, w: 12 }, { v: 50, w: 8 }, { v: 75, w: 5 }, { v: 100, w: 2 },
  ],
  packs: [
    { id: 'p1', coins: 1200, price: '0,99 US$', name: 'Puñado', icon: 'coin' },
    { id: 'p2', coins: 4000, price: '2,99 US$', name: 'Bolsa', icon: 'coins' },
    { id: 'p3', coins: 7000, price: '4,99 US$', name: 'Saco', icon: 'coins' },
    { id: 'p4', coins: 15000, price: '9,99 US$', name: 'Cofre', icon: 'coins', tag: 'POPULAR' },
    { id: 'p5', coins: 32000, price: '19,99 US$', name: 'Arcón', icon: 'coins' },
    { id: 'p6', coins: 90000, price: '49,99 US$', name: 'Tesoro del templo', icon: 'coins', tag: 'MEJOR VALOR' },
  ],
};

export const RARITY = {
  normal: { label: 'NORMAL', color: '#C9D2B4', price: 1500 },
  especial: { label: 'ESPECIAL', color: '#6CC24A', price: 6000 },
  mitico: { label: 'MÍTICO', color: '#5FA0E0', price: 12000 },
  legendario: { label: 'LEGENDARIO', color: '#E8B04A', price: 25000 },
  temporada: { label: 'TEMPORADA', color: '#E87532', price: 0 },
};

// ------------------------------------------------------------------ skins
// Every skin is drawn with the pieces cut from its sheet (assets/skins3/<id>/: head, tongue,
// body modules A/B/C, special module, tail). The catalogue itself is generated by tools/build_v6.py.
// trail = particles left behind, aura = soft glow, colors = crumble particles on defeat.
const sk = (id, name, rarity, trail, colors, extra = {}) => ({ id, name, rarity, trail, colors, fx: colors[1], tongue: '#C7354A', ...extra });

const BASIC = [
  ['rojo', 'Roja', 250], ['azul', 'Azul', 250], ['amarillo', 'Amarilla', 300],
  ['morado', 'Morada', 300], ['naranja', 'Naranja', 350], ['rosa', 'Rosa', 350],
  ['turquesa', 'Turquesa', 400], ['negro', 'Negra', 450], ['blanco', 'Blanca', 500],
];

// Season 1 (Harvest Moon Hollow): free track Maíz + Farol, premium track Espantapájaros, Bruja and Calabaza.
export const SEASON_SKINS = { free: ['maiz', 'farol'], prem: ['espantapajaros', 'bruja', 'calabaza'] };

// Per-skin render tuning, set by eye in the game: thick = body width, headW = head width vs the body,
// tailLen = max tail length in cells.
const TUNE = {};

// Short English name of every skin, shown on the gallery cards in every language (never translated).
const SHORT = {
  basica: 'GREEN',
  basica_rojo: 'RED',
  basica_azul: 'BLUE',
  basica_amarillo: 'YELLOW',
  basica_morado: 'PURPLE',
  basica_naranja: 'ORANGE',
  basica_rosa: 'PINK',
  basica_turquesa: 'TEAL',
  basica_negro: 'BLACK',
  basica_blanco: 'WHITE',
  nube: 'CLOUD',
  gargola: 'GARGOYLE',
  cactus: 'CACTUS',
  escarabajo: 'SCARAB',
  cuervo: 'RAVEN',
  prisma: 'PRISM',
  mecanismo: 'GEARS',
  ambar: 'AMBER',
  origami: 'ORIGAMI',
  eclipse: 'ECLIPSE',
  robot: 'ROBOT',
  musgo: 'MOSS',
  celestial: 'CELESTIAL',
  monarca: 'MONARCH',
  wyrmlunar: 'MOON WYRM',
  serafin: 'SERAPH',
  arandano: 'BERRY',
  ladrillo: 'BRICK',
  fenix: 'PHOENIX',
  girasol: 'SUNFLOWER',
  miel: 'HONEY',
  tempestad: 'STORM',
  aurora: 'AURORA',
  unicornio: 'UNICORN',
  cebra: 'ZEBRA',
  trueno: 'THUNDER',
  arenisca: 'SANDSTONE',
  pizarra: 'SLATE',
  coral: 'CORAL',
  kraken: 'KRAKEN',
  pirata: 'PIRATE',
  coloso: 'COLOSSUS',
  ciervo: 'STAG',
  niebla: 'MIST',
  volcan: 'VOLCANO',
  vikinga: 'VIKING',
  oni: 'ONI',
  menta: 'MINT',
  caramelo: 'CANDY',
  ola: 'WAVE',
  panda: 'PANDA',
  tigre: 'TIGER',
  vidriera: 'GLASS',
  arrecife: 'REEF',
  cacao: 'COCOA',
  arcade: 'ARCADE',
  piton: 'PYTHON',
  emperador: 'EMPEROR',
  sirena: 'MERMAID',
  bruja: 'WITCH',
  calabaza: 'PUMPKIN',
  maiz: 'CORN',
  espantapajaros: 'SCARECROW',
  farol: 'LANTERN',
};

const ALL_SKINS = [
  sk('basica', 'Serpiente Básica Verde', 'normal', 'dust', BASIC_COLORS.basica, { basic: true, price: 0, desc: 'La compañera de siempre. Ágil, fiel y lista para crecer.' }),
  ...BASIC.map(([id, nm, price]) => sk('basica_' + id, 'Serpiente Básica ' + nm, 'normal', 'dust',
    BASIC_COLORS['basica_' + id], { basic: true, price, desc: 'La serpiente básica de siempre, ahora en otro color.' })),
  ...SKIN_LIST.map((s) => sk(s.id, s.name, s.rarity, s.trail, s.colors, {
    desc: s.desc, tongueImg: s.tongueImg, season: s.rarity === 'temporada', ...(TUNE[s.id] || {}),
  })),
];

ALL_SKINS.forEach((s) => { s.short = SHORT[s.id] || s.id.toUpperCase(); });
export const SKINS = ALL_SKINS;
export const skinById = (id) => ALL_SKINS.find((s) => s.id === id) || SKINS[0];
export const skinPrice = (s) => s.price ?? RARITY[s.rarity].price;

// Duel rivals: each one wears a skin from the collection.
export const BOTS = {
  easy: { ...skinById('basica_turquesa'), id: 'bot_easy', name: 'MOSS WORM', art: 'basica_turquesa', label: 'FÁCIL', speed: 0.78, mistake: 0.18, aggression: 0, target: 10 },
  medium: { ...skinById('arenisca'), id: 'bot_medium', name: 'RUST VIPER', art: 'arenisca', label: 'MEDIO', speed: 0.95, mistake: 0.05, aggression: 0.25, target: 12 },
  hard: { ...skinById('oni'), id: 'bot_hard', name: 'CRIMSON FANG', art: 'oni', label: 'DIFÍCIL', speed: 1.02, mistake: 0, aggression: 0.7, target: 15 },
};

// ------------------------------------------------------------------ maps
export const MAPS = [
  { id: 1, name: 'EMERALD JUNGLE', sheet: 8, hazard: 'hz_pillar' },
  { id: 2, name: 'SAKURA GARDEN', sheet: 0, hazard: 'hz_bridge', tint: '#5A2A2A' },
  { id: 3, name: 'LOST GREEK RUINS', sheet: 6, hazard: 'hz_temple', tint: '#8A7A5A' },
  { id: 4, name: 'MUSHROOM GROVE', sheet: 3, hazard: 'hz_spores', tint: '#4A2A5A' },
  { id: 5, name: 'DESERT TOMBS', sheet: 10, hazard: 'hz_quicksand', tint: '#9A6A2A' },
  { id: 6, name: 'TOXIC WASTES', sheet: 5, hazard: 'hz_mud', tint: '#3A5A1A' },
  { id: 7, name: 'FROZEN TUNDRA', sheet: 7, hazard: 'hz_ice', tint: '#6A9AC0' },
  { id: 8, name: 'CRYSTAL CAVES', sheet: 14, hazard: 'hz_portal', tint: '#2A4A7A' },
  { id: 9, name: 'SUNKEN ATLANTIS', sheet: 1, hazard: 'hz_wind', tint: '#1A5A6A' },
  { id: 10, name: 'VOLCANO CORE', sheet: 4, hazard: 'hz_lava', tint: '#7A2A10' },
  { id: 11, name: 'PIRATE COVE', sheet: 13, hazard: 'hz_block', tint: '#6A4A2A' },
  { id: 12, name: 'MEDIEVAL CASTLE', sheet: 9, hazard: 'hz_spikes', tint: '#3A3A4A' },
  { id: 13, name: 'SKY GARDENS', sheet: 12, hazard: 'hz_void', tint: '#6A8AA8' },
  { id: 14, name: 'MOON TEMPLE', sheet: 2, hazard: 'hz_dark', tint: '#3A4A8A' },
  { id: 15, name: 'HAUNTED GRAVEYARD', sheet: 15, hazard: 'hz_skull', tint: '#2A2A3A' },
  { id: 16, name: 'CYBER CITY', sheet: 11, hazard: 'hz_block', tint: '#4A1A7A' },
].map((m) => ({ ...m, key: `maps/key${String(m.sheet).padStart(2, '0')}.jpg` }));


// Monthly season map (20 levels, guardians at 10 and 20). Season 1 = Harvest Moon Hollow.
export const SEASON_MAP = { id: 17, name: 'HARVEST MOON HOLLOW', key: 'maps/season1.jpg', hazard: 'hz_dark', levels: 20, freeLevels: 5, skin: 'calabaza' };

// ------------------------------------------------------------------ levels
// Legend for ASCII layouts (duel arena): . floor | P pillar | T totem | C column (2 wide, with c) | W wall block
const L = (rows) => rows.map((r) => r.padEnd(12, '.'));

// Story difficulty presets (used by maps.js for terrain and by storyLevel for pace).
export const DIFFS = {
  easy: { id: 'easy', label: 'FÁCIL', speed: 0.85, target: 1, obst: 0.6, hazard: 0.5, bridges: 1, reward: 0.6, gold: 1.3, color: '#7FD05A' },
  normal: { id: 'normal', label: 'NORMAL', speed: 1, target: 1, obst: 0.9, hazard: 0.8, bridges: 0, reward: 1, gold: 1, color: '#E8B04A' },
  hard: { id: 'hard', label: 'DIFÍCIL', speed: 1.12, target: 1, obst: 1.15, hazard: 1.1, bridges: -1, reward: 1.7, gold: 0.8, color: '#E0524A' },
};

// Orbs needed: easy 8-20, normal 10-26, hard 12-31 (never more than a 216-cell board can comfortably hold)
const TARGET_BASE = { easy: 8, normal: 10, hard: 12 };
const TARGET_MAP = { easy: 0.3, normal: 0.4, hard: 0.5 };
const TARGET_LVL = { easy: 0.9, normal: 1.1, hard: 1.3 };

export function storyLevel(map, n, diff = 'normal') {
  if (map === 17) {
    const g = n === 10 || n === 20;
    return {
      map, n, diff: 'normal', mapInfo: SEASON_MAP, season: true,
      target: Math.round(11 + 0.85 * (n - 1)) + (g ? 2 : 0),
      speed: 3.9 + 0.055 * (n - 1) + (g ? 0.2 : 0),
      goldChance: Math.min(0.3, 0.1 + 0.01 * n),
      reward: 60 + 10 * n,
      spawn: { x: 5, y: 14, dir: 'up', len: 4 },
      guardian: g,
    };
  }
  const d = DIFFS[diff] || DIFFS.normal;
  return {
    map, n, diff: d.id, mapInfo: MAPS[map - 1],
    target: Math.round(TARGET_BASE[d.id] + TARGET_MAP[d.id] * (map - 1) + TARGET_LVL[d.id] * (n - 1)),
    speed: (3.7 + 0.05 * (map - 1) + 0.1 * (n - 1)) * d.speed,
    goldChance: Math.min(0.35, (0.08 + (0.1 * (n - 1)) / 9) * d.gold),
    reward: Math.round(ECONOMY.levelReward(map, n) * d.reward),
    spawn: { x: 5, y: 14, dir: 'up', len: 4 },
    guardian: n === 10,
  };
}

// Guided level 0 (first game): small target, easy terrain, scripted in game.js
export const tutorialLevel = () => ({
  map: 1, n: 4, diff: 'easy', mapInfo: MAPS[0], tutorial: true, target: 5, speed: 3.3, goldChance: 0, reward: 0,
  spawn: { x: 5, y: 14, dir: 'up', len: 4 }, guardian: false,
});

export const DUEL_LAYOUT = L(['', '', '', '..Cc....Cc..', '', '', '', '', '..P......P..', '..P......P..', '', '', '', '', '..Cc....Cc..', '', '', '']);

export const MODES = [
  { id: 'story', name: 'HISTORIA', icon: 'mode_story', img: 'maps/key08.jpg', desc: '16 mapas · 160 niveles', sub: 'Recoge los orbes y supera cada nivel' },
  { id: 'classic', name: 'CLÁSICO', icon: 'mode_classic', img: 'modes/classic.jpg', desc: 'Sobrevive y bate tu récord', sub: 'La velocidad sube cada 10 orbes' },
  { id: 'frenzy', name: 'ORBES FRENÉTICOS', icon: 'mode_frenzy', img: 'modes/frenzy.jpg', desc: '60 segundos · solo orbes dorados', sub: 'Sin muros: cruza los bordes' },
  { id: 'duel', name: 'DUELO', icon: 'mode_duel', img: 'modes/duel.jpg', desc: 'Vence al rival', sub: 'Fácil · Medio · Difícil' },
];

export const TIPS = [
  'Los orbes dorados te hacen crecer x3, pero vas el doble de rápido.',
  'Encadena orbes en menos de 3 segundos para multiplicar tu puntuación.',
  'En Orbes Frenéticos no hay muros: sal por un borde y entra por el otro.',
  'En el Duelo, si la cabeza del rival toca tu cuerpo, el rival pierde.',
  'El nivel 10 de cada mapa es el Guardián: prepárate.',
];
