// Generated by tools/build_assets.py (skin_modules)
export const SKIN_MODS = {
 "harvest": {
  "variants": 3,
  "specials": 2
 },
 "cosmic": {
  "variants": 3,
  "specials": 1
 },
 "solar": {
  "variants": 0,
  "specials": 1
 },
 "ember": {
  "variants": 0,
  "specials": 1
 },
 "umbra": {
  "variants": 0,
  "specials": 1
 },
 "kitsune": {
  "variants": 0,
  "specials": 1
 },
 "toxic": {
  "variants": 0,
  "specials": 1
 },
 "mushroom": {
  "variants": 0,
  "specials": 1
 },
 "vampire": {
  "variants": 0,
  "specials": 1
 },
 "abyssal": {
  "variants": 0,
  "specials": 2
 },
 "knight": {
  "variants": 0,
  "specials": 1
 }
};
